import type { Article, InternalLink, PerformanceMetric } from './types'

export const MOCK_ARTICLES: Article[] = [
  {
    id: '1',
    title: 'What Is CSRD Double Materiality? A Practical Guide for Mid-Sized Companies',
    slug: 'csrd-double-materiality-guide',
    status: 'published',
    topic_input: 'CSRD double materiality assessment for mid-sized companies',
    target_audience: 'Sustainability managers',
    human_input: 'Most guides skip the practical side. Focus on the actual steps a sustainability manager would take in week 1. Mention that many companies are confusing CSRD materiality with GRI materiality — this is a real pain point I keep hearing.',
    brief_json: {
      keyword: 'CSRD double materiality',
      outline: [
        'What is double materiality under CSRD?',
        'Why mid-sized companies need to prepare now',
        'Step-by-step: conducting a double materiality assessment',
        'Common mistakes and how to avoid them',
        'Tools and frameworks that help',
      ],
      angle: 'Practical, step-by-step guide aimed at sustainability managers at mid-sized EU companies who are approaching CSRD compliance for the first time.',
      audience: 'Sustainability managers',
      key_points: [
        'Double materiality requires assessing both impact materiality and financial materiality',
        'EFRAG provides detailed guidance through the ESRS standards',
        'Stakeholder engagement is mandatory, not optional',
        'Start with a gap analysis against ESRS disclosure requirements',
      ],
    },
    draft_html: '<h2>What Is Double Materiality Under CSRD?</h2><p>The Corporate Sustainability Reporting Directive (CSRD) introduces a concept that fundamentally changes how companies think about sustainability reporting: <strong>double materiality</strong>.</p><p>Unlike traditional financial materiality — which asks "does this sustainability issue affect our bottom line?" — double materiality adds a second lens: "does our company affect this sustainability issue?"</p><h3>Why This Matters for Mid-Sized Companies</h3><p>If your company has more than 250 employees, exceeds €50M in revenue, or has over €25M in total assets, CSRD applies to you from financial year 2025. That means your first report is due in 2026.</p><p>The assessment is not a box-ticking exercise. It requires genuine stakeholder engagement, data collection across your value chain, and a structured process that can withstand external assurance.</p><h3>Step-by-Step: Conducting Your Assessment</h3><ol><li><strong>Map your value chain</strong> — Identify upstream suppliers, downstream customers, and affected communities.</li><li><strong>Identify potential sustainability matters</strong> — Use the ESRS topical standards as your starting list.</li><li><strong>Engage stakeholders</strong> — This is mandatory. Document who you consulted and how their input shaped your assessment.</li><li><strong>Apply the double materiality test</strong> — For each matter, assess both impact materiality (your effect on the world) and financial materiality (the world\'s effect on your finances).</li><li><strong>Set thresholds and document decisions</strong> — Explain why certain matters were deemed material or not.</li></ol><h3>Common Mistakes</h3><ul><li>Treating the assessment as a one-off rather than an ongoing process</li><li>Skipping stakeholder engagement or treating it superficially</li><li>Confusing CSRD materiality with GRI or ISSB materiality definitions</li></ul>',
    final_html: null,
    keywords: ['CSRD', 'double materiality', 'sustainability reporting', 'ESRS'],
    meta_description: 'Learn how to conduct a CSRD double materiality assessment. A practical, step-by-step guide for mid-sized companies preparing for compliance.',
    visual_suggestions: [
      { type: 'cover' as const, description: 'Hero illustration: two overlapping lenses (impact + financial) converging on a sustainability report, in Coolset brand blue tones', placement: 'Article header / cover image' },
      { type: 'supporting' as const, description: 'Infographic: Double materiality matrix showing impact vs financial materiality axes', placement: 'After the "What is double materiality" section' },
      { type: 'supporting' as const, description: 'Flowchart: 5-step assessment process', placement: 'Before the step-by-step section' },
    ],
    revision_notes: null,
    webflow_item_id: 'wf_abc123',
    webflow_slug: 'csrd-double-materiality-guide',
    created_at: '2025-03-10T09:00:00Z',
    updated_at: '2025-03-12T14:30:00Z',
  },
  {
    id: '2',
    title: 'Scope 3 Emissions: How to Measure What You Cannot Directly Control',
    slug: 'scope-3-emissions-measurement',
    status: 'draft',
    topic_input: 'How to measure and reduce Scope 3 emissions across the supply chain',
    target_audience: 'Procurement & supply chain managers',
    human_input: 'Emphasise that spend-based is a totally valid starting point — too many companies get paralysed trying to collect primary data from day one. Also mention that supplier engagement is where the real leverage is, not just better calculations.',
    brief_json: {
      keyword: 'scope 3 emissions measurement',
      outline: [
        'What are Scope 3 emissions and why do they matter?',
        'The 15 Scope 3 categories explained',
        'Data collection strategies for supply chain emissions',
        'Calculation methods: spend-based vs activity-based',
        'Setting reduction targets with SBTi',
      ],
      angle: 'Practical measurement guide for companies starting their Scope 3 journey, with emphasis on data collection challenges and realistic approaches.',
      audience: 'Procurement & supply chain managers',
      key_points: [
        'Scope 3 typically represents 70-90% of a company\'s total carbon footprint',
        'Start with the most material categories, not all 15',
        'Spend-based estimates are a valid starting point before moving to primary data',
        'Supplier engagement is the biggest challenge and opportunity',
      ],
    },
    draft_html: '<h2>What Are Scope 3 Emissions?</h2><p>Scope 3 emissions are all the indirect greenhouse gas emissions that occur across your value chain — both upstream and downstream. Unlike Scope 1 (direct emissions from owned operations) and Scope 2 (indirect emissions from purchased energy), Scope 3 captures everything else.</p><p>For most companies, this is where the bulk of their carbon footprint lives. <strong>On average, Scope 3 accounts for 70–90% of a company\'s total emissions.</strong></p><h3>The 15 Categories</h3><p>The GHG Protocol divides Scope 3 into 15 categories, split between upstream and downstream activities:</p><ul><li><strong>Upstream:</strong> Purchased goods & services, capital goods, fuel & energy, transportation, waste, business travel, employee commuting, leased assets</li><li><strong>Downstream:</strong> Transportation & distribution, processing, use of sold products, end-of-life treatment, leased assets, franchises, investments</li></ul><h3>Where to Start</h3><p>Trying to measure all 15 categories at once is a recipe for analysis paralysis. Instead, focus on your most material categories first. For most manufacturing companies, this means <strong>Category 1 (Purchased Goods & Services)</strong> and <strong>Category 4 (Upstream Transportation)</strong>.</p>',
    final_html: null,
    keywords: ['scope 3 emissions', 'supply chain emissions', 'carbon footprint', 'GHG protocol'],
    meta_description: 'A practical guide to measuring Scope 3 emissions. Learn data collection strategies, calculation methods, and how to prioritise across the 15 GHG Protocol categories.',
    visual_suggestions: [
      { type: 'cover' as const, description: 'Abstract illustration: supply chain network with emission clouds at each node, showing the breadth of Scope 3', placement: 'Article header / cover image' },
      { type: 'supporting' as const, description: 'Diagram: Scope 1, 2, 3 emissions boundaries with examples', placement: 'After the opening paragraph' },
      { type: 'supporting' as const, description: 'Table: 15 Scope 3 categories with relevance indicators by industry', placement: 'After the categories list' },
    ],
    revision_notes: null,
    webflow_item_id: null,
    webflow_slug: null,
    created_at: '2025-03-12T11:00:00Z',
    updated_at: '2025-03-13T16:45:00Z',
  },
  {
    id: '3',
    title: 'Carbon Offsets vs Carbon Credits: What Sustainability Teams Need to Know',
    slug: 'carbon-offsets-vs-credits',
    status: 'review',
    topic_input: 'Difference between carbon offsets and carbon credits, and when to use each',
    target_audience: 'Sustainability managers',
    human_input: 'Take a balanced but honest stance — offsets have a reputation problem and some of it is deserved. The key message should be: reduce first, offset what you genuinely cannot eliminate yet. Mention the greenwashing risk explicitly.',
    brief_json: {
      keyword: 'carbon offsets vs carbon credits',
      outline: [
        'Definitions: offsets vs credits — clearing up the confusion',
        'The voluntary vs compliance market distinction',
        'Quality standards: Gold Standard, Verra, and beyond',
        'When offsets make sense (and when they don\'t)',
        'Building a credible carbon strategy',
      ],
      angle: 'Clarifying a commonly confused topic with a balanced, practical perspective that helps teams make informed decisions.',
      audience: 'Sustainability managers',
      key_points: [
        'Carbon credits and offsets are often used interchangeably but have distinct meanings in different market contexts',
        'Quality varies enormously — always check the verification standard',
        'Offsets should complement, never replace, direct emissions reductions',
        'The regulatory landscape is shifting toward greater scrutiny of offset claims',
      ],
    },
    draft_html: '<h2>Carbon Offsets vs Carbon Credits: Clearing Up the Confusion</h2><p>If you have spent any time researching corporate climate strategies, you have likely encountered the terms <strong>carbon offsets</strong> and <strong>carbon credits</strong> used almost interchangeably. They are related but not identical, and the distinction matters.</p><p>A <strong>carbon credit</strong> is a tradeable certificate representing one tonne of CO₂ equivalent either reduced or removed from the atmosphere. Credits exist in both compliance markets (like the EU ETS) and voluntary markets.</p><p>A <strong>carbon offset</strong> specifically refers to using credits from the voluntary market to compensate for emissions you have not yet eliminated. When a company says it is "offsetting" its emissions, it is purchasing voluntary credits to balance out its remaining footprint.</p><h3>Quality Matters More Than Quantity</h3><p>Not all credits are created equal. The market has been plagued by projects that overstated their impact or would have happened regardless of credit financing (known as the "additionality" problem).</p><p>Look for credits verified under recognised standards:</p><ul><li><strong>Gold Standard</strong> — Generally considered the highest quality, with strong co-benefit requirements</li><li><strong>Verra (VCS)</strong> — The largest voluntary registry by volume</li><li><strong>ACR and CAR</strong> — North America-focused registries</li></ul>',
    final_html: null,
    keywords: ['carbon offsets', 'carbon credits', 'voluntary carbon market', 'climate strategy'],
    meta_description: 'Understand the real difference between carbon offsets and carbon credits. Learn about quality standards, market types, and how to build a credible carbon strategy.',
    visual_suggestions: [
      { type: 'cover' as const, description: 'Split visual: one side showing a factory with offset arrows, the other showing verified carbon credit certificates', placement: 'Article header / cover image' },
      { type: 'supporting' as const, description: 'Comparison table: Carbon offsets vs carbon credits side by side', placement: 'After the definitions section' },
    ],
    revision_notes: 'Good structure but needs more specific guidance on how to evaluate credit quality. Add a practical checklist.',
    webflow_item_id: null,
    webflow_slug: null,
    created_at: '2025-03-13T08:30:00Z',
    updated_at: '2025-03-14T10:15:00Z',
  },
  {
    id: '4',
    title: 'ESG Reporting Frameworks Compared: GRI, ISSB, ESRS, and TCFD',
    slug: 'esg-reporting-frameworks-compared',
    status: 'brief',
    topic_input: 'Comparison of major ESG reporting frameworks and which one to choose',
    target_audience: 'ESG analysts & reporting teams',
    human_input: 'Everyone is overwhelmed by the alphabet soup. Make a clear decision matrix at the end. Key insight: most companies will need multiple frameworks, so the question isn\'t which one but which combination.',
    brief_json: {
      keyword: 'ESG reporting frameworks comparison',
      outline: [
        'Overview of the framework landscape in 2025',
        'GRI: the impact-focused standard',
        'ISSB (IFRS S1/S2): the investor-focused standard',
        'ESRS: the EU\'s mandatory standard under CSRD',
        'TCFD: the climate disclosure foundation',
        'Decision matrix: which framework(s) do you need?',
      ],
      angle: 'A clear-headed comparison that helps sustainability teams navigate the alphabet soup of frameworks without getting overwhelmed.',
      audience: 'ESG analysts & reporting teams',
      key_points: [
        'Most companies will need to work with multiple frameworks',
        'ESRS is mandatory for EU companies under CSRD',
        'ISSB is gaining traction as the global investor-focused baseline',
        'GRI and ESRS have high interoperability by design',
        'TCFD recommendations are now embedded in ISSB and ESRS',
      ],
    },
    draft_html: null,
    final_html: null,
    keywords: ['ESG reporting', 'GRI', 'ISSB', 'ESRS', 'TCFD'],
    meta_description: null,
    visual_suggestions: null,
    revision_notes: null,
    webflow_item_id: null,
    webflow_slug: null,
    created_at: '2025-03-14T15:00:00Z',
    updated_at: '2025-03-14T15:00:00Z',
  },
  {
    id: '5',
    title: 'EUDR Compliance: What Importers Need to Do Before December 2025',
    slug: 'eudr-compliance-importers-guide',
    status: 'cms_ready',
    topic_input: 'EUDR compliance requirements and timeline for importers',
    target_audience: 'Compliance officers',
    human_input: 'Urgency is the angle — December 2025 is right around the corner and most importers are not ready. Focus on the practical due diligence steps, not just the regulation text.',
    brief_json: null,
    draft_html: '<h2>EUDR: The Clock Is Ticking for Importers</h2><p>The EU Deforestation Regulation (EUDR) enters full application on 30 December 2025. If your company imports commodities like soy, palm oil, coffee, cocoa, rubber, wood, or cattle products into the EU, you need a compliance plan now.</p>',
    final_html: '<h2>EUDR: The Clock Is Ticking for Importers</h2><p>The EU Deforestation Regulation (EUDR) enters full application on 30 December 2025. If your company imports commodities like soy, palm oil, coffee, cocoa, rubber, wood, or cattle products into the EU, you need a compliance plan now.</p><p>This guide covers the key requirements and practical steps to get ready.</p>',
    keywords: ['EUDR', 'deforestation regulation', 'supply chain compliance'],
    meta_description: 'Everything importers need to know about EUDR compliance. Key requirements, deadlines, and practical steps before December 2025.',
    visual_suggestions: null,
    revision_notes: null,
    webflow_item_id: null,
    webflow_slug: null,
    created_at: '2025-03-08T10:00:00Z',
    updated_at: '2025-03-14T09:00:00Z',
  },
]

export const MOCK_LINKS: InternalLink[] = [
  {
    id: 'link-1',
    source_article_id: '1',
    target_article_id: '3',
    anchor_text: 'carbon offset strategies',
    context_snippet: 'Companies preparing for CSRD should also consider their carbon offset strategies as part of their broader climate disclosures.',
    status: 'applied',
    created_at: '2025-03-12T15:00:00Z',
  },
  {
    id: 'link-2',
    source_article_id: '1',
    target_article_id: '2',
    anchor_text: 'Scope 3 emissions measurement',
    context_snippet: 'Double materiality often surfaces Scope 3 emissions measurement as a key area requiring attention.',
    status: 'suggested',
    created_at: '2025-03-12T15:00:00Z',
  },
]

export const MOCK_METRICS: PerformanceMetric[] = [
  {
    id: 'metric-1',
    article_id: '1',
    date: '2025-03-14',
    impressions: 2340,
    clicks: 187,
    avg_position: 8.3,
    ctr: 0.08,
    tracked_keyword: 'CSRD double materiality',
    created_at: '2025-03-14T06:00:00Z',
  },
  {
    id: 'metric-2',
    article_id: '1',
    date: '2025-03-13',
    impressions: 1890,
    clicks: 142,
    avg_position: 9.1,
    ctr: 0.075,
    tracked_keyword: 'CSRD double materiality',
    created_at: '2025-03-13T06:00:00Z',
  },
]
